-- Dufaka-Go schema. Status numbers and column names match the dujiaoka storefront and admin.

CREATE TABLE goods_group (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gp_name     varchar(200) NOT NULL,
    is_open     smallint NOT NULL DEFAULT 1,
    ord         integer NOT NULL DEFAULT 1,
    created_at  timestamptz,
    updated_at  timestamptz,
    deleted_at  timestamptz
);

CREATE TABLE goods (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id             integer NOT NULL REFERENCES goods_group (id),
    gd_name              varchar(200) NOT NULL,
    gd_description       varchar(200) NOT NULL,
    gd_keywords          varchar(200) NOT NULL,
    picture              text,
    retail_price         numeric(10, 2) DEFAULT 0,
    actual_price         numeric(10, 2) NOT NULL DEFAULT 0,
    in_stock             integer NOT NULL DEFAULT 0,
    sales_volume         integer DEFAULT 0,
    ord                  integer DEFAULT 1,
    buy_limit_num        integer NOT NULL DEFAULT 0,
    buy_prompt           text,
    description          text,
    type                 smallint NOT NULL DEFAULT 1,
    wholesale_price_cnf  text,
    other_ipu_cnf        text,
    api_hook             text,
    is_open              smallint NOT NULL DEFAULT 1,
    created_at           timestamptz,
    updated_at           timestamptz,
    deleted_at           timestamptz
);

CREATE TABLE carmis (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_id    integer NOT NULL REFERENCES goods (id),
    status      smallint NOT NULL DEFAULT 1,
    is_loop     smallint NOT NULL DEFAULT 0,
    carmi       text NOT NULL,
    reserved_order_id bigint,
    created_at  timestamptz,
    updated_at  timestamptz,
    deleted_at  timestamptz
);
CREATE INDEX idx_carmis_goods_unsold ON carmis (goods_id, status) WHERE deleted_at IS NULL;

CREATE TABLE coupons (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount    numeric(10, 2) NOT NULL DEFAULT 0,
    is_use      smallint NOT NULL DEFAULT 1,
    is_open     smallint NOT NULL DEFAULT 1,
    coupon      varchar(150) NOT NULL UNIQUE,
    ret         integer NOT NULL DEFAULT 0,
    created_at  timestamptz,
    updated_at  timestamptz,
    deleted_at  timestamptz
);

CREATE TABLE coupons_goods (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_id    integer NOT NULL REFERENCES goods (id),
    coupons_id  integer NOT NULL REFERENCES coupons (id)
);

CREATE TABLE pays (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_name         varchar(200) NOT NULL,
    pay_check        varchar(50) NOT NULL UNIQUE,
    pay_method       smallint NOT NULL,
    pay_client       smallint NOT NULL DEFAULT 1,
    merchant_id      varchar(200),
    merchant_key     text,
    merchant_pem     text NOT NULL,
    pay_handleroute  varchar(200) NOT NULL,
    is_open          smallint NOT NULL DEFAULT 1,
    created_at       timestamptz,
    updated_at       timestamptz,
    deleted_at       timestamptz
);

CREATE TABLE orders (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_sn                 varchar(150) NOT NULL UNIQUE,
    goods_id                 integer NOT NULL REFERENCES goods (id),
    coupon_id                integer DEFAULT 0,
    title                    varchar(200) NOT NULL,
    type                     smallint NOT NULL DEFAULT 1,
    goods_price              numeric(10, 2) NOT NULL DEFAULT 0,
    buy_amount               integer NOT NULL DEFAULT 1,
    coupon_discount_price    numeric(10, 2) NOT NULL DEFAULT 0,
    wholesale_discount_price numeric(10, 2) NOT NULL DEFAULT 0,
    total_price              numeric(10, 2) NOT NULL DEFAULT 0,
    actual_price             numeric(10, 2) NOT NULL DEFAULT 0,
    search_pwd               varchar(200) DEFAULT '',
    email                    varchar(200) NOT NULL,
    info                     text,
    pay_id                   integer REFERENCES pays (id),
    buy_ip                   varchar(50) NOT NULL,
    trade_no                 varchar(200) DEFAULT '',
    status                   smallint NOT NULL DEFAULT 1,
    coupon_ret_back          smallint NOT NULL DEFAULT 0,
    created_at               timestamptz,
    updated_at               timestamptz,
    deleted_at               timestamptz
);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cldx_minor bigint, ADD COLUMN IF NOT EXISTS cldx_expires_at bigint;
CREATE INDEX idx_orders_email ON orders (email);

CREATE TABLE emailtpls (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tpl_name     varchar(150) NOT NULL,
    tpl_content  text NOT NULL,
    tpl_token    varchar(50) NOT NULL UNIQUE,
    created_at   timestamptz,
    updated_at   timestamptz,
    deleted_at   timestamptz
);

CREATE TABLE admin_users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(120) NOT NULL UNIQUE,
    password        varchar(80) NOT NULL,
    name            varchar(255) NOT NULL,
    avatar          varchar(255),
    remember_token  varchar(100),
    created_at      timestamptz,
    updated_at      timestamptz
);

CREATE TABLE admin_roles (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(50) NOT NULL,
    slug        varchar(50) NOT NULL UNIQUE,
    created_at  timestamptz,
    updated_at  timestamptz
);

CREATE TABLE admin_permissions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(50) NOT NULL,
    slug         varchar(50) NOT NULL,
    http_method  varchar(255),
    http_path    text,
    "order"      integer NOT NULL DEFAULT 0,
    parent_id    bigint NOT NULL DEFAULT 0,
    created_at   timestamptz,
    updated_at   timestamptz
);

CREATE TABLE admin_menu (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   bigint NOT NULL DEFAULT 0,
    "order"     integer NOT NULL DEFAULT 0,
    title       varchar(50) NOT NULL,
    icon        varchar(50),
    uri         varchar(50),
    extension   varchar(50) NOT NULL DEFAULT '',
    show        smallint NOT NULL DEFAULT 1,
    created_at  timestamptz,
    updated_at  timestamptz
);

CREATE TABLE admin_role_users (
    role_id     bigint NOT NULL REFERENCES admin_roles (id),
    user_id     bigint NOT NULL REFERENCES admin_users (id),
    created_at  timestamptz,
    updated_at  timestamptz,
    PRIMARY KEY (role_id, user_id)
);

CREATE TABLE admin_role_permissions (
    role_id        bigint NOT NULL REFERENCES admin_roles (id),
    permission_id  bigint NOT NULL REFERENCES admin_permissions (id),
    created_at     timestamptz,
    updated_at     timestamptz,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE admin_role_menu (
    role_id     bigint NOT NULL REFERENCES admin_roles (id),
    menu_id     bigint NOT NULL REFERENCES admin_menu (id),
    created_at  timestamptz,
    updated_at  timestamptz,
    PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE admin_permission_menu (
    permission_id  bigint NOT NULL REFERENCES admin_permissions (id),
    menu_id        bigint NOT NULL REFERENCES admin_menu (id),
    created_at     timestamptz,
    updated_at     timestamptz,
    PRIMARY KEY (permission_id, menu_id)
);

CREATE TABLE admin_settings (
    slug        varchar(100) PRIMARY KEY,
    value       text NOT NULL,
    created_at  timestamptz,
    updated_at  timestamptz
);

-- Site settings. Same keys as the original system-setting form. Not a new admin page.
CREATE TABLE settings (
    key         varchar(100) PRIMARY KEY,
    value       text NOT NULL,
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Internal retries for mail, push, and product callbacks.
CREATE TABLE jobs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        varchar(40) NOT NULL,
    payload     jsonb NOT NULL,
    run_at      timestamptz NOT NULL,
    attempts    integer NOT NULL DEFAULT 0,
    last_error  text,
    done_at     timestamptz
);
CREATE INDEX idx_jobs_due ON jobs (run_at) WHERE done_at IS NULL;
